# Generated by Django 4.0.5 on 2022-08-28 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=200)),
                ('Place_of_residence', models.TextField(max_length=200)),
                ('age', models.IntegerField(max_length=100)),
            ],
        ),
    ]
