# Generated by Django 4.0.5 on 2022-08-18 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=400)),
                ('mosque', models.TextField(max_length=200)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
