# Generated by Django 4.1 on 2022-08-24 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('musqname', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('time', models.DateTimeField()),
                ('catg', models.BooleanField()),
            ],
        ),
    ]
